# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Unity_Test01' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOS_Unity_Test01
  pod 'Masonry'

end
